language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools
    - extra

    - build-tools-25.0.0
    - android-26

script:
  - ./gradlew build
  - ./gradlew build test
