language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew build
  - ./gradlew build test

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
